config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/jquery-1" => "pages#jquery_1"
  get "/jquery-2" => "pages#jquery_2"
  get "/jquery-3" => "pages#jquery_3"
  get "/jquery-4" => "pages#jquery_4"
  get "/jquery-5" => "pages#jquery_5"

  resources :posts do
    member do
      post "like" => "posts#like"
      post "unlike" => "posts#unlike"
      post "toggle_flag" => "posts#toggle_flag"
      post "rate" => "posts#rate"
    end
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :category, :optional => true
  validates_presence_of :content
  belongs_to :user

  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, :source => :user
  has_many :scores, :class_name => "PostScore"

  def find_like(user)
    self.likes.where( :user_id => user.id ).first
  end

  def find_score(user)
    user && self.scores.where( :user_id => user.id ).first
  end

  def average_score
    self.scores.average(:score)
  end
end

app/models/post_score.rb
class PostScore < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  has_many :likes, :dependent => :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  def display_name
    # # 取 email 的前半来显示，如果你也可以另开一个字段是 nickname 让用户可以自己编辑显示名称
    self.email.split("@").first
  end

  def is_admin?
    role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :only => [:create, :destroy]

  def index
    @posts = Post.order("id DESC").limit(20)

    if params[:max_id]
      @posts = @posts.where( "id < ?", params[:max_id])
    end

    respond_to do |format|
      format.html  # 如果客户端要求 HTML，则回传 index.html.erb
      format.js    # 如果客户端要求 JavaScript，回传 index.js.erb
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.save

  end

  def update
    # sleep(1)
    @post = Post.find(params[:id])
    @post.update!( post_params )

    render :json => { :id => @post.id, :message => "ok"}
  end

  def destroy
    @post = current_user.posts.find(params[:id]) # 只能删除自己的贴文
    @post.destroy

    render :json => { :id => @post.id }
  end

  def like
    @post = Post.find(params[:id])
    unless @post.find_like(current_user)  # 如果已经按讚过了，就略过不再新增
      Like.create( :user => current_user, :post => @post)
    end

  end

  def unlike
    @post = Post.find(params[:id])
    like = @post.find_like(current_user)
    like.destroy

    render "like"
  end

  def toggle_flag
    @post = Post.find(params[:id])

    if @post.flag_at
      @post.flag_at = nil
    else
      @post.flag_at = Time.now
    end

    @post.save!

    render :json => { :message => "ok", :flag_at => @post.flag_at, :id => @post.id }
  end


  def rate
    @post = Post.find(params[:id])

    existing_score = @post.find_score(current_user)
    if existing_score
      existing_score.update( :score => params[:score] )
    else
      @post.scores.create( :score => params[:score], :user => current_user )
    end

    render :json => { :average_score => @post.average_score }
  end

  protected

  def post_params
    params.require(:post).permit(:content, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxPostingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>

      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>

      <% if current_user %>
         <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
        <%= link_to('修改密码', edit_registration_path(:user)) %>
      <% else %>
        <%= link_to('注册', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>

      <%= link_to "jQuery 练习一", jquery_1_path %> |
      <%= link_to "jQuery 练习二", jquery_2_path %> |
      <%= link_to "jQuery 练习三", jquery_3_path %> |
      <%= link_to "jQuery 练习四", jquery_4_path %> |
      <%= link_to "jQuery 练习五", jquery_5_path %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/jquery_1.html.erb
<script>
// 这是 javascript 注解
// 也可以缩写成 $(function() {
$(document).ready(function(){
  $("#my-click").click(function(){
    $("#foo").html('<h1>zoo</h1>');
  })
})
</script>

<p>
  <a id="my-click">Click Me</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

app/views/pages/jquery_2.html.erb
<p>
  <a id="my-open-click">Open</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <a id="my-hide-click">Hide</a>
  <p>bar</p>
</div>


<script>
  $("#foo").hide();

  $("#my-open-click").click(function(){
    $("#foo").show();
  })

  $("#my-hide-click").click(function(){
    $("#foo").hide();
  })
</script>

app/views/pages/jquery_3.html.erb
<p>
  <a id="my-toggle-click">Toggle</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<script>
  $("#foo").hide();   // 先马上藏起来

  $("#my-toggle-click").hover(function(){
    $("#foo").fadeToggle();   // 移过去会有开关的效果
  })

</script>

app/views/pages/jquery_4.html.erb
<p>
  <a id="my-replace-click">Replace</a>
  <a id="my-remove-click">Remove</a>
  <a id="my-remove-all-click">Remove All</a>
</p>

<div id="foo" style="border: 1px solid red;">
  <p>bar</p>
</div>

<div class="zoo"><p>a</p></div>
<div class="zoo"><p>b</p></div>
<div class="zoo"><p>c</p></div>

<script>
  $("#my-replace-click").click(function(){
    $("#foo").replaceWith('<div id="foo" style="border:1px solid green"><p>foo</p></div>');
  })

  $("#my-remove-click").click(function(){
    $("#foo").remove();
  })

  $("#my-remove-all-click").click(function(){
    $(".zoo").remove();
  })
</script>

app/views/pages/jquery_5.html.erb
<style>
  .error {
    color: red;
  }
  .success {
    color: green;
  }
</style>

<p>
  <a id="my-add-class-click">Add Class</a>

  <a id="my-remove-class-click">Remove Class</a>
</p>

<div id="foo">
  <h1>bar</h1>
</div>

<script>
  $("#my-add-class-click").click(function(){
    $("#foo").removeClass('error');
    $("#foo").addClass('success');
  })

  $("#my-remove-class-click").click(function(){
    $("#foo").removeClass('success');
    $("#foo").addClass('error');
  })
</script>

app/views/posts/_like.html.erb
<% if post.liked_users.any? %>
  <%= post.liked_users.map{ |u| u.display_name }.join(",") %> 点了赞
<% end %>

<% if current_user # 有登入才可以按讚 %>
  <% if post.find_like(current_user) %>
    <%= link_to "取消讚", unlike_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% else %>
    <%= link_to "讚", like_post_path(post), :method => :post, :remote => true, :class => "btn btn-primary" %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="panel panel-default">
  <div class="panel-heading">
    <%= post.user.display_name %>
  </div>
  <div class="panel-body">
    <span id="post-thumbsup-<%= post.id %>" class="label label-success"><%= post.likes.count %> 👍</span>
    <span class="average-score"><%= post.average_score %></span>
    <div class="raty" data-score="<%= post.find_score(current_user).try(:score) || 0 %>" data-score-url="<%= rate_post_path(post) %>"></div>

    <%= post.content %>

      <div class="text-right">

       <span id="post-like-<%= post.id %>">
         <%= render :partial => "like", :locals => { :post => post } %>
       </span>

        <% if current_user && post.user == current_user %>
          <p class="text-right">
            <%= link_to "Delete", post_path(post), :class => "delete-post btn btn-danger" %>
          </p>
        <% end %>
      </div>
  </div>

  <div class="panel-footer">
    <% if current_user && current_user.is_admin? %>
      <%= select_tag "category_id[#{post.id}]", options_for_select(Category.all.map{ |x| [x.name, x.id]}, post.category_id),
          :data => { :url => post_path(post) }, :prompt => "请选择分类", :class => "select_category" %>

      <label>
      <%= check_box_tag "mark_flag[#{post.id}]", 1, post.flag_at.present?,
            :data => { :url => toggle_flag_post_path(post) }, :class => "toggle-flag" %> 标记为垃圾
        <span id="post-flag-<%= post.id %>"><%= post.flag_at %></span>
      </label>
    <% end %>
  </div>
</div>

app/views/posts/create.js.erb
 <% if @post.valid? %>
   $("#post-list").prepend("<%=j render :partial => "post", :locals => { :post => @post } %>");
   $("#post_content").val("");
 <% else %>
   alert("贴文失败");
 <% end %>

app/views/posts/index.html.erb
<%= form_for Post.new, :remote => true do |f| %>
  <div class="form-group">
    <%= f.text_area :content, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

<div id="post-list">
  <% @posts.each do |post| %>
  <%= render :partial => "post", :locals => { :post => post} %>
  <% end %>
</div>

<script>
  // 这会绑 click 事件到所有有 `.delete-post` class 的元素上，也就是所有的删除按钮
  $("#post-list").on('click', ".delete-post", function(evt){
    // `evt` 是浏览器的事件物件，evt.preventDefault(); 会终止这个元素的默认行为：
    // 超连结 a 的默认行为是跳到下一页，如果没有这行的话，送出 ajax 后会跳去 show page
    evt.preventDefault();
    // this 是个特别的变量，代表触发事件的元素。使用 attr 可以读取元素的属性，这里要拿到超连结的网址
    var url = $(this).attr("href");
    var that = this;

    // 送出 Ajax
    $.ajax({
      url: url,
      method: 'DELETE',
      dataType: 'json', // 要求服务器回传 json
      success: function(data){   // data 就是服务器回传的 JSON 资料
        $(that).closest(".panel").remove();
      }
    })
  })

  // 记下目前画面最小的贴文 ID
  var current_post_id = <%= @posts.last.id %>;

  // 当捲轴动的时候，会触发这个事件
  $(window).scroll(function(){
    // 当捲到最下面的时候
    if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
      var url = "/posts?max_id=" + current_post_id;
      if (url) {
        $.ajax({
          method: "GET",
          url: url,
          dataType: "script"
        })
      } else {
        console.log("data ended")
      }
    }
  })

  $("#post-list").on('change', ".toggle-flag", function(){
    var url = $(this).data("url");
    var that = this;

    $.ajax({
      url: url,
      method: "POST",
      dataType: "json",
      success: function(data){
        if ( data["flag_at"] ) {
          $(that).closest("label").find("span").html(data["flag_at"])
        } else {
          $(that).closest("label").find("span").html("")
        }
      }
    });
  });

   $("#post-list").on('change', ".select_category", function(){
     var url = $(this).data("url");
     var that = this;

     $.ajax({
       url: url,
       method: "PATCH",
       dataType: "json",
       data: {
         post: {
           category_id: $(this).val()
         }
       },
       beforeSend: function(){
         $(that).after( $(' <img src="/images/ajax-loader.gif" id="ajax-loading"> ') );
       },
       complete: function(){
         $("#ajax-loading").remove();
       }
     });
   });

   $(".raty").raty({
     path: '/images/',
     score: function() { return $(this).data('score'); },
     click: function(score) {
       var that = this;
       $.ajax({
         url: $(this).data("score-url"),
         method: "POST",
         data: { score: score },
         dataType: "json",
         success: function(data){
           $(that).closest(".panel-body").find(".average-score").html( data["average_score"] );
         }
       })
     }
   });
</script>

app/views/posts/index.js.erb
<% @posts.each do |post| %>
  $("#post-list").append("<hr>")
  $("#post-list").append("<%=j render :partial => "post", :locals => { :post => post } %>");
<% end %>

<% if @posts.any? %>
var current_post_id = <%= @posts.last.id %>;
<% end %>

app/views/posts/like.js.erb
str = "<%=j render :partial => "like", :locals => { :post => @post } %>";
$("#post-like-<%= @post.id %>").html(str);

$("#post-thumbsup-<%= @post.id %>").html("<%= @post.likes.count %>" + " 👍");